/*
 * This question is asked by Google. You are given two strings, s and t which only consist of lowercase letters. 
 * t is generated by shuffling the letters in s as well as potentially adding an additional random character. 
 * Return the letter that was randomly added to t if it exists, otherwise, return ’  ‘.
 * Note: You may assume that at most one additional character can be added to t.
*/

#include <iostream>
using namespace std;

int main() {
    string s,t;
    cin>>s>>t;

    int freqArrayForS[26] = {0};
    int freqArrayForT[26] = {0};

    for(int i = 0; i<s.size(); i++){
        freqArrayForS[s[i]-'a']++;
    } 

    for(int i = 0; i<t.size(); i++){
        freqArrayForT[t[i]-'a']++;
    } 

    bool hasDiffChar = false;
    int i = 0;
    for(; i<26; i++){
        if(freqArrayForS[i] != freqArrayForT[i]){
            hasDiffChar = true;
            break;
        }
    }
    if(hasDiffChar){
        char c = i + 97;
        cout<<c<<"\n";
    } else {
        cout<<" \n";
    }
}